
package com.client_port;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://service_port.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Greeting")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Greeting", targetNamespace = "http://service_port.com/", className = "com.client_port.Greeting")
    @ResponseWrapper(localName = "GreetingResponse", targetNamespace = "http://service_port.com/", className = "com.client_port.GreetingResponse")
    @Action(input = "http://service_port.com/HelloService/GreetingRequest", output = "http://service_port.com/HelloService/GreetingResponse")
    public String greeting(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
